import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    nav_saveurs: "Saveurs",
    nav_concept: "Concept",
    nav_coffrets: "Coffrets",
    nav_why: "Pourquoi nous",
    hero_title: "Là où la Nature devient Énergie",
    hero_subtitle: "Billes d'énergie aux fruits lyophilisés 100% naturels",
    hero_cta: "Commander maintenant",
    student_fuel_title: "Boostez vos Révisions naturellement",
    student_fuel_subtitle: "Le Fuel des Étudiants",
    cart_empty: "Votre panier est vide",
    cart_discover: "Découvrir la collection",
    cart_total: "Total",
    cart_checkout: "Finaliser ma commande",
    checkout_title: "Finaliser votre commande",
    checkout_name: "Nom Complet",
    checkout_phone: "Téléphone",
    checkout_address: "Adresse de livraison",
    checkout_confirm: "Confirmer la commande",
    unit_price_note: "Tarif à l'unité (7 MAD/bille)",
    btn_commander: "Commander",
    btn_discover: "Découvrir",
    btn_add_cart: "Ajouter au panier",
    btn_quick_buy: "Achat rapide",
    footer_tagline: "Le fuel naturel des étudiants. Énergie saine, fruits lyophilisés, sans compromis. Fait avec passion au Maroc.",
    footer_made_with: "Fait avec ❤️ pour les étudiants",
    home_hero_tag: "VitaOrigen · أحسن بلااااان 😋",
    home_hero_title_1: "Là où la Nature",
    home_hero_title_2: "devient",
    home_hero_title_3: "Énergie",
    home_marquee_1: "100% Naturel",
    home_marquee_2: "Fruits Lyophilisés",
    home_marquee_3: "Sans Sucre",
    home_marquee_4: "Énergie Saine",
    home_marquee_5: "Fait au Maroc",
    home_how_tag: "Comment ça marche",
    home_how_title_1: "Un Voyage de la",
    home_how_title_2: "Nature",
    home_how_title_3: "à votre main",
    home_step_1_title: "Lyophilisation Pure",
    home_step_1_desc: "Nous utilisons des fruits cueillis à maturité, puis lyophilisés pour préserver 97% des nutriments et du goût authentique.",
    home_step_2_title: "Pressage à Froid",
    home_step_2_desc: "Les fruits sont mélangés à des flocons d'avoine premium et pressés à froid sans aucune cuisson pour garder toute l'énergie.",
    home_step_3_title: "Zéro Compromis",
    home_step_3_desc: "Aucun sucre ajouté, aucun conservateur. Juste la pureté du fruit dans une bille d'énergie pratique.",
    home_student_advice_tag: "Conseil Révision",
    home_student_advice_desc: "Une bille VitaOrigen toutes les 2 heures permet de maintenir un niveau de glucose stable pour une concentration maximale.",
    home_student_title_1: "Boostez vos",
    home_student_title_2: "Révisions",
    home_student_title_3: "naturellement",
    home_student_feat_1_t: "Zéro Crash Énergétique",
    home_student_feat_1_d: "Contrairement au café ou aux boissons sucrées, nos fruits lyophilisés libèrent l'énergie progressivement.",
    home_student_feat_2_t: "Prêt pour la Bibliothèque",
    home_student_feat_2_d: "Silencieux, sans odeur et ne tache pas les doigts. Le snack discret idéal pour bosser en silence.",
    home_student_feat_3_t: "Focus & Mémoire",
    home_student_feat_3_d: "Riche en antioxydants naturels qui aident à combattre la fatigue mentale pendant les examens.",
    home_student_cta: "Découvrir la collection Étudiant",
    home_faq_tag: "Des questions ?",
    home_faq_title: "Questions Fréquentes",
    home_faq_1_q: "Qu'est-ce que la lyophilisation ?",
    home_faq_1_a: "C'est un processus de séchage à froid qui retire l'eau du fruit tout en préservant sa structure, ses vitamines et ses saveurs naturelles.",
    home_faq_2_q: "Y a-t-il du sucre ajouté ?",
    home_faq_2_a: "Absolument aucun. La sucrosité de nos billes provient uniquement du sucre naturel présent dans les fruits.",
    home_faq_3_q: "Quelle est la durée de conservation ?",
    home_faq_3_a: "Grâce à notre processus de fabrication, nos billes se conservent parfaitement pendant 6 mois dans un endroit sec.",
    saveurs_tag: "La Collection",
    saveurs_title_1: "Nos 8",
    saveurs_title_2: "Saveurs",
    saveurs_title_3: "Signature",
    flavor_strawberry_name: "Fraise",
    flavor_strawberry_desc: "Une explosion de douceur fruitée et acidulée.",
    flavor_blueberry_name: "Myrtille",
    flavor_blueberry_desc: "L'énergie profonde et riche de la myrtille sauvage.",
    flavor_raspberry_name: "Framboise",
    flavor_raspberry_desc: "Parfumée et pétillante, la framboise dans toute sa pureté.",
    flavor_cherry_name: "Cerise",
    flavor_cherry_desc: "La douceur classique et intense de la cerise noire.",
    flavor_banana_name: "Banane",
    flavor_banana_desc: "Une texture onctueuse et gourmande pour un boost naturel.",
    flavor_pineapple_name: "Ananas",
    flavor_pineapple_desc: "Un voyage tropical avec l'éclat de l'ananas frais.",
    flavor_orange_name: "Orange",
    flavor_orange_desc: "Rafraîchissante et tonique, pleine de vitamine naturelle.",
    flavor_kiwi_name: "Kiwi",
    flavor_kiwi_desc: "Le twist exotique et acidulé du kiwi mûr.",
    tag_natural: "100% NATUREL",
    coffret_tag: "Artisanat sur mesure",
    coffret_title_1: "Composez votre",
    coffret_title_2: "Chef-d'œuvre",
    coffret_capacity: "Capacité",
    coffret_billes: "billes",
    coffret_filling: "Remplissage",
    coffret_empty: "Panier Vide",
    coffret_complete: "Compléter le Coffret",
    coffret_checkout: "Passer à la Caisse",
    coffret_select_pack: "Choisir un coffret",
    coffret_select_desc: "Sélectionnez la taille de votre coffret sur la gauche pour commencer la composition.",
    coffret_recap: "Récapitulatif",
    coffret_clear: "Tout vider",
    concept_tag: "Nos Formats",
    concept_title_1: "Le Coffret",
    concept_title_2: "Idéal",
    concept_tab_1: "Pack de 4",
    concept_tab_2: "Pack de 8",
    concept_tab_3: "Pack de 16",
    concept_desc_1: "Le format idéal pour vos pauses rapides. 4 billes d'énergie pure pour vous accompagner durant vos sessions de révision.",
    concept_desc_2: "Notre format le plus populaire. 8 saveurs variées pour une semaine pleine de vitalité et de concentration.",
    concept_desc_3: "Le format prestige pour les plus gourmands ou à partager. 16 billes pour une énergie durable sans compromis.",
    concept_bullets_1: "Prix: 26 MAD,Format de poche,Idéal pour la journée,Énergie instantanée",
    concept_bullets_2: "Prix: 54 MAD,Assortiment complet,Parfait pour la semaine,Emballage premium",
    concept_bullets_3: "Prix: 110 MAD,Le meilleur rapport qualité/prix,Format familial ou partage,Stock d'énergie longue durée"
  },
  ar: {
    nav_saveurs: "النكهات",
    nav_concept: "المفهوم",
    nav_coffrets: "الصناديق",
    nav_why: "لماذا نحن",
    hero_title: "حيثما تصبح الطبيعة طاقة",
    hero_subtitle: "كرات طاقة بالفواكه المجففة طبيعية 100%",
    hero_cta: "اطلب الآن",
    student_fuel_title: "عزز تركيزك في المراجعة بشكل طبيعي",
    student_fuel_subtitle: "وقود الطلاب",
    cart_empty: "سلتك فارغة",
    cart_discover: "اكتشف المجموعة",
    cart_total: "المجموع",
    cart_checkout: "إتمام الطلب",
    checkout_title: "إتمام طلبك",
    checkout_name: "الاسم الكامل",
    checkout_phone: "رقم الهاتف",
    checkout_address: "عنوان التوصيل",
    checkout_confirm: "تأكيد الطلب",
    unit_price_note: "سعر الحبة (7 درهم)",
    btn_commander: "اطلب الآن",
    btn_discover: "اكتشف",
    btn_add_cart: "أضف إلى السلة",
    btn_quick_buy: "شراء سريع",
    footer_tagline: "وقود الطلاب الطبيعي. طاقة صحية، فواكه مجففة، بدون مساومات. صنع بشغف في المغرب.",
    footer_made_with: "صنع بـ ❤️ للطلاب",
    home_hero_tag: "VitaOrigen · أحسن بلااااان 😋",
    home_hero_title_1: "حيثما تصبح",
    home_hero_title_2: "الطبيعة",
    home_hero_title_3: "طاقة",
    home_marquee_1: "100% طبيعي",
    home_marquee_2: "فواكه مجففة",
    home_marquee_3: "بدون سكر",
    home_marquee_4: "طاقة صحية",
    home_marquee_5: "صنع في المغرب",
    home_how_tag: "كيف يعمل؟",
    home_how_title_1: "رحلة من",
    home_how_title_2: "الطبيعة",
    home_how_title_3: "إلى يدك",
    home_step_1_title: "تجفيف طبيعي نقي",
    home_step_1_desc: "نستخدم فواكه مقطوفة عند النضج، ثم نجففها للحفاظ على 97٪ من العناصر الغذائية والطعم الأصلي.",
    home_step_2_title: "ضغط بارد",
    home_step_2_desc: "تُخلط الفواكه مع رقائق الشوفان الفاخرة وتُضغط على البارد بدون أي طهي للحفاظ على كل الطاقة.",
    home_step_3_title: "بدون مساومات",
    home_step_3_desc: "لا سكر مضاف، لا مواد حافظة. فقط نقاء الفاكهة في كرة طاقة عملية.",
    home_student_advice_tag: "نصيحة للمراجعة",
    home_student_advice_desc: "حبة واحدة من VitaOrigen كل ساعتين تساعد في الحفاظ على مستوى مستقر من السكر لتركيز أقصى.",
    home_student_title_1: "عزز",
    home_student_title_2: "مراجعتك",
    home_student_title_3: "بشكل طبيعي",
    home_student_feat_1_t: "بدون هبوط مفاجئ في الطاقة",
    home_student_feat_1_d: "على عكس القهوة أو المشروبات السكرية، تطلق فواكهنا المجففة الطاقة تدريجيًا.",
    home_student_feat_2_t: "مثالي للمكتبة",
    home_student_feat_2_d: "صامت، بدون رائحة ولا يترك أثراً على الأصابع. الوجبة الخفيفة المثالية للعمل في صمت.",
    home_student_feat_3_t: "التركيز والذاكرة",
    home_student_feat_3_d: "غني بمضادات الأكسدة الطبيعية التي تساعد في محاربة التعب الذهني أثناء الامتحانات.",
    home_student_cta: "اكتشف مجموعة الطلاب",
    home_faq_tag: "هل لديك أسئلة؟",
    home_faq_title: "الأسئلة المتكررة",
    home_faq_1_q: "ما هو التجفيف بالتجميد (Lyophilisation)؟",
    home_faq_1_a: "هي عملية تجفيف باردة تزيل الماء من الفاكهة مع الحفاظ على بنيتها وفيتاميناتها ونكهاتها الطبيعية.",
    home_faq_2_q: "هل يوجد سكر مضاف؟",
    home_faq_2_a: "أبداً. حلاوة كراتنا تأتي فقط من السكر الطبيعي الموجود في الفاكهة.",
    home_faq_3_q: "ما هي مدة الصلاحية؟",
    home_faq_3_a: "بفضل عملية التصنيع لدينا، تبقى الكرات في حالة ممتازة لمدة 6 أشهر في مكان جاف.",
    saveurs_tag: "المجموعة",
    saveurs_title_1: "نكهاتنا",
    saveurs_title_2: "الثمانية",
    saveurs_title_3: "المميزة",
    flavor_strawberry_name: "فراولة",
    flavor_strawberry_desc: "انفجار من الحلاوة الطبيعية والمنعشة.",
    flavor_blueberry_name: "توت أزرق",
    flavor_blueberry_desc: "طاقة عميقة وغنية من التوت البري.",
    flavor_raspberry_name: "توت أحمر",
    flavor_raspberry_desc: "عطرية ومنعشة، التوت الأحمر في أنقى صوره.",
    flavor_cherry_name: "كرز",
    flavor_cherry_desc: "الحلاوة الكلاسيكية والمكثفة للكرز الأسود.",
    flavor_banana_name: "موز",
    flavor_banana_desc: "قوام كريمي ولذيذ لدفعة طاقة طبيعية.",
    flavor_pineapple_name: "أناناس",
    flavor_pineapple_desc: "رحلة استوائية مع إشراقة الأناناس الطازج.",
    flavor_orange_name: "برتقال",
    flavor_orange_desc: "منعش ومنشط، مليء بالفيتامينات الطبيعية.",
    flavor_kiwi_name: "كيوي",
    flavor_kiwi_desc: "لمسة غريبة ومنعشة من الكيوي الناضج.",
    tag_natural: "طبيعي 100%",
    coffret_tag: "صناعة يدوية حسب الطلب",
    coffret_title_1: "صمم",
    coffret_title_2: "صندوقك",
    coffret_title_3: "الخاص",
    coffret_capacity: "السعة",
    coffret_billes: "حبات",
    coffret_filling: "التعبئة",
    coffret_empty: "السلة فارغة",
    coffret_complete: "أكمل الصندوق",
    coffret_checkout: "إتمام الطلب",
    coffret_select_pack: "اختر صندوقاً",
    coffret_select_desc: "اختر حجم صندوقك من اليسار لبدء التصميم.",
    coffret_recap: "ملخص",
    coffret_clear: "مسح الكل",
    concept_tag: "أحجامنا",
    concept_title_1: "الصندوق",
    concept_title_2: "المثالي",
    concept_tab_1: "مجموعة 4 حبات",
    concept_tab_2: "مجموعة 8 حبات",
    concept_tab_3: "مجموعة 16 حبة",
    concept_desc_1: "الحجم المثالي لاستراحاتك السريعة. 4 كرات من الطاقة النقية لمرافقتك أثناء جلسات المراجعة.",
    concept_desc_2: "حجمنا الأكثر شعبية. 8 نكهات متنوعة لأسبوع مليء بالحيوية والتركيز.",
    concept_desc_3: "الحجم الفاخر لمحبي التذوق أو للمشاركة. 16 كرة لطاقة مستدامة بدون مساومات.",
    concept_bullets_1: "السعر: 26 درهم,حجم جيب عملي,مثالي لليوم,طاقة فورية",
    concept_bullets_2: "السعر: 54 درهم,تشكيلة كاملة,مثالي للأسبوع,تغليف فاخر",
    concept_bullets_3: "السعر: 110 درهم,أفضل قيمة مقابل السعر,حجم عائلي أو للمشاركة,مخزون طاقة طويل الأمد"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('vita_lang');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('vita_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
